### ISSUE TITLE
hg19.100kb.windows.bed

### ISSUE THREAD

**Issue by PengfeiInTuebingen** [magnitov/pentads#10]
Hi,
I was following the 'paper_code/02_technical_tests.sh' instruction to calculate compartments size, and then I want to calculate each compartments strength, I just don't understand what the 'hg19.100kb.windows.bed' file looks like, is it the chromosome size file?
Best,
Pengfei

**Comment by magnitov** [comment]
Hi @pengfei50,

Here is how the file format looks like, it's just bed with bins of your desired size:
> chrom   start   end
> chr1    0       100000
> chr1    100000  200000
> chr1    200000  300000
> chr1    300000  400000
> chr1    400000  500000

You can create this with **`bedtools makewindows -g [chromosome sizes file] -w [window]`** function.

**Comment by PengfeiInTuebingen** [comment]
Thank you very much!
Best,
Pengfei
--
Pengfei Liu
Ph.D. student
Department of Algal Development and Evolution
Max Planck Institute for Biology Tübingen
Max-Planck-Ring 5
72076 Tübingen
Tel.: +49 0176 4454 4310
https://www.eb.tuebingen.mpg.de/de/department-of-algal-development-and-evolution/
