### ISSUE TITLE
Log2 scale

### ISSUE THREAD

**Issue by katikoshak** [magnitov/pentads#15]
Hello! Could you please tell me whether there is a possibility to calculate average compartment and visualize it in log2-scale?

**Comment by magnitov** [comment]
Hi @katikoshak ,

That's possible. Just modify lines 98, 120 and 147 where `plt.imshow()` functions are located in the plotting script (https://github.com/magnitov/pentad/blob/development/src/plot_pentad.py). You just have to add np.log2() for the first argument and remove norm parameter which adds colorbar in log scale.

Best,
Mikhail

**Comment by katikoshak** [comment]
Thanks a lot!
