### ISSUE TITLE
get_pentads_trans.py fails to work well based on cooltools(v0.5.1)

### ISSUE THREAD

**Issue by Alexlsy** [magnitov/pentads#9]
get_pentads_trans.py is based on cooltools(v0.3.2). However, environment.yml does not specify the version of cooltools so it will create an environment with the latest version of cooltools by default. Anyone who tries to run get_pentads_trans.py needs to uninstall cooltools first and reinstall cooltools(v0.3.2) with command "conda install -c bioconda cooltools=0.3.2"

**Comment by magnitov** [comment]
Hi @Alexlsy, 

Thanks for reporting this! I have changed the scripts so that they are compatible with the latest cooltools release (v0.5.0 and later). I have also update YML file to reflect this. Please feel free to reopen the issue if the problem is still there.

Best,
Mikhail
